# Site settings
title: Hortonworks Tutorials
email: do-not-reply@hortonworks.com
description: > # this means to ignore newlines until "baseurl:"
  A collection of tutorials for Hortonworks' Hadoop distribution (HDP)
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://tutorials.blanco.io" # the base hostname & protocol for your site
twitter_username: hortonworks
github_username:  hortonworks

# Build settings
markdown: kramdown
